### ISSUE TITLE
concert_scheduler_requests crash

### ISSUE THREAD

**Issue by piyushk** [utexas-bwi/concert_scheduling#26]
I'm afraid the error message is a bit too cryptic for me to explain. And I can't reproduce this error with certainty.

```
[ERROR] [WallTime: 1398033132.501574] bad callback: <bound method CompatibilityTreeScheduler._ros_subscriber_concert_client_changes of <concert_schedulers.compatibility_tree_scheduler.scheduler.CompatibilityTreeScheduler object at 0x17fd848>>
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/topics.py", line 682, in _invoke_callback
    cb(msg)
  File "/home/piyushk/rocon_catkin_ws/src/rocon_concert/concert_schedulers/src/concert_schedulers/compatibility_tree_scheduler/scheduler.py", line 118, in _ros_subscriber_concert_client_changes
    self._update()
  File "/home/piyushk/rocon_catkin_ws/src/rocon_concert/concert_schedulers/src/concert_schedulers/compatibility_tree_scheduler/scheduler.py", line 250, in _update
    reply.grant(resources)
  File "/home/piyushk/rocon_catkin_ws/src/concert_scheduling/concert_scheduler_requests/src/concert_scheduler_requests/transitions.py", line 306, in grant
    self._transition(EVENT_GRANT, reason=Request.NONE)
  File "/home/piyushk/rocon_catkin_ws/src/concert_scheduling/concert_scheduler_requests/src/concert_scheduler_requests/transitions.py", line 224, in _transition
    + ' in state ' + str(self.msg.status))
TransitionError: invalid event grant in state 5
```

**Comment by jack-oquin** [comment]
State 5 is Request.CANCELING: "The requester wishes to cancel this request, but the scheduler has not yet confirmed that it is closed."

See: http://docs.ros.org/hydro/api/scheduler_msgs/html/msg/Request.html

In that state, it should probably be calling close() and not grant():

 http://farnsworth.csres.utexas.edu/docs/concert_scheduler_requests/html/transitions.html

I'll try to generate a human-readable exception message.

**Comment by jack-oquin** [comment]
Is this still a problem with concert_scheduler_requests?

**Comment by piyushk** [comment]
I cannot reproduce it anymore, now that https://github.com/robotics-in-concert/rocon_concert/issues/221 has been solved. Thanks!

Closing.
